select * from CUSTOMER_APPLICATION;

--META_CUSTOMER_STATUS
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('OPN','OPEN','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('PFC','Pending From Checker','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('RFC','Rejected From Checker','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('CLD','Closed','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('DEL','Deleted','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('REOPEN','Reopen','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('DREO','Request Delete from Reopen','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('DCLD','Request Delete from Closed','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CUSTOMER_STATUS (CUSTOMER_STATUS_CODE ,CUSTOMER_STATUS_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('DRFC','Request Delete from Rejected','N','SYSTEM',1,SYSDATE, SYSDATE);


--META_CHECKER_ACTION
insert into META_CHECKER_ACTION (CHECKER_ACTION_CODE ,CHECKER_ACTION_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('APR','Approved','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_CHECKER_ACTION (CHECKER_ACTION_CODE ,CHECKER_ACTION_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('REJ','Rejected','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);

--META_USER_ROLE
insert into META_USER_ROLE (ROLE_CODE ,ROLE_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('MKR','Maker','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into META_USER_ROLE (ROLE_CODE ,ROLE_DESCRIPTION , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('CKR','Checker','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);

--USERS
insert into USERS (USER_NAME ,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL_ADDRESS , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('TEST1','PASSWORD','Test','1','test1@test.com','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into USERS (USER_NAME ,PASSWORD,FIRST_NAME,LAST_NAME,EMAIL_ADDRESS , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('TEST2','PASSWORD','Test','2','test2@test.com','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);

--USER_ROLE
insert into USER_ROLE (USER_NAME ,ROLE_CODE , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('TEST1','MKR','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);
insert into USER_ROLE (USER_NAME ,ROLE_CODE , INACTIVE_IND , AUDIT_USER_ID,AUDIT_STATUS	,AUDIT_REASON, AUDIT_ENTRY_DATETIME, AUDIT_MODIFIED_DATETIME)values('TEST2','CKR','N','SYSTEM',1,'INITIAL DATA',SYSDATE, SYSDATE);

commit;
